language: ruby
rvm:
  - "2.5.8"
cache: bundler
env:
  # http://docs.travis-ci.com/user/environment-variables/#Global-Variables
  global:
    - BITCOINORG_BUILD_TYPE=deployment

before_install:
  - "gem update --system 3.0.6"
  - "gem install bundler -v 1.17.3"

script: make travis
