#!/usr/bin/env ruby

require 'html-proofer'

path_to_check = ARGV[0].nil? ? "./_site" : ARGV[0]

## Internal-links-only check, ported from the html-proofer 2.x API
## (require path, class name, and option names changed in 4.x/5.x).
HTMLProofer.check_directory(
  path_to_check,
  {
    :disable_external => true,
    :allow_missing_href => true,
    :enforce_https => false,
    :check_internal_hash => false,
    :checks => ["Links"],
    :ignore_urls => [
      '#',
      /^$/,
      /^\/bin/,
      /^.*\.(pdf|PDF)$/,
      'bitcoin:bc1qp6ejw8ptj9l9pkscmlf8fhhkrrjeawgpyjvtq8',
      /^\/stats/
    ],
    :swap_urls => {
      /(css|png|rss|pdf|jpg|asc|xml)$/ => '\1$',
      /^([^#]+[^\/$])$/ => '\1.html',
      /^(.+)(#.+)/ => '\1.html\2',
      /\/(.html#.+)/ => '\1',
      /\$$/ => '',
    },
  }
).run
