#!/usr/bin/env ruby
# frozen_string_literal: false

# This file is licensed under the MIT License (MIT) available on
# http://opensource.org/licenses/MIT.

# Print any warning from JSHint for custom javascript code.

require 'jshintrb'

path_to_check = ARGV[0] || './_site/js'

Dir.foreach(path_to_check) do |file|
  next unless /\.js$/.match(file)

  res = Jshintrb.report(File.read(path_to_check + '/' + file), :jshintrc)
  print path_to_check + '/' + file + "\n" + res unless res.empty?
end
