#!/bin/bash

if [[ -z ${1} || -z ${2} ]]; then
	echo 'You must provide language code and language name. Ex : ./_contrib/translate fr "Français"'
	exit
fi

cp -R en ${1}
cp _layouts/base-en.html _layouts/base-${1}.html
sed -i "s_layout: base-en_layout: base-${1}_g" ${1}/*.html
sed -i "s_lang: en_lang: ${1}_g" ${1}/*.html
sed -i "s_lang: en_lang: ${1}_g" _layouts/base-${1}.html
sed -i "/id: ${1}/d" _config.yml
sed -i "/${1}: /d" _config.yml
sed -i "/langs:/a - ${1}: ${2}" _config.yml
sed -i "s_- ${1}: ${2}_  ${1}: ${2}_g" _config.yml
sed -i "/langsorder:/a- id: ${1}" _config.yml
sed -i "s_- id:${1}_- id: ${1}_g" _config.yml
sed -i "/all:/a- ${1}: " _config.yml
sed -i "s_- ${1}_  ${1}_g" _config.yml
